### ISSUE TITLE
Quota

### ISSUE THREAD

**Issue by glennmichaelmejias** [lesnitsky/flutter_localstorage#88]
What is the quota? Is it editable?

DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'asdf' exceeded the quota.
    at Storage.[_setItem] (http://localhost:56654/dart_sdk.js:100499:27)
    at Storage.[dartx._set] (http://localhost:56654/dart_sdk.js:100437:25)
    at Storage.update (http://localhost:56654/dart_sdk.js:23149:22)
    at web.DirUtils.new._writeToStorage (http://localhost:56654/packages/localstorage/src/directory/web.dart.lib.js:121:35)
    at _writeToStorage.next (<anonymous>)
    at runBody (http://localhost:56654/dart_sdk.js:40590:34)
    at Object._async [as async] (http://localhost:56654/dart_sdk.js:40621:7)
    at web.DirUtils.new.[_writeToStorage] (http://localhost:56654/packages/localstorage/src/directory/web.dart.lib.js:118:20)
    at web.DirUtils.new.flush (http://localhost:56654/packages/localstorage/src/directory/web.dart.lib.js:88:35)
    at localstorage.LocalStorage._internal._flush (http://localhost:56654/packages/localstorage/localstorage.dart.lib.js:129:28)
    at _flush.next (<anonymous>)
    at runBody (http://localhost:56654/dart_sdk.js:40590:34)
    at Object._async [as async] (http://localhost:56654/dart_sdk.js:40621:7)
    at localstorage.LocalStorage._internal.[_flush] (http://localhost:56654/packages/localstorage/localstorage.dart.lib.js:127:20)
    at localstorage.LocalStorage._internal.setItem (http://localhost:56654/packages/localstorage/localstorage.dart.lib.js:111:28)
    at setItem.next (<anonymous>)
    at http://localhost:56654/dart_sdk.js:40571:33
    at _RootZone.runUnary (http://localhost:56654/dart_sdk.js:40441:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:56654/dart_sdk.js:35363:29)
    at handleValueCallback (http://localhost:56654/dart_sdk.js:35931:49)
    at Function._propagateToListeners (http://localhost:56654/dart_sdk.js:35969:17)
    at _Future.new.[_completeWithValue] (http://localhost:56654/dart_sdk.js:35817:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:56654/dart_sdk.js:35838:35)
    at Object._microtaskLoop (http://localhost:56654/dart_sdk.js:40708:13)
    at _startMicrotaskLoop (http://localhost:56654/dart_sdk.js:40714:13)
    at http://localhost:56654/dart_sdk.js:36191:9

**Comment by lesnitsky** [comment]
https://stackoverflow.com/questions/2989284/what-is-the-max-size-of-localstorage-values
No, the quota can't be increased, this is a browser limitation.
